# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BulkImportJobCollection(Model):
    """A collection of bulk import job objects.

    All required parameters must be populated in order to send to Azure.

    :param value: Required. The list of bulk import job objects.
    :type value: list[~azure.digitaltwins.core.models.BulkImportJob]
    :param next_link: A URI to retrieve the next page of results.
    :type next_link: str
    """

    _validation = {
        'value': {'required': True},
    }

    _attribute_map = {
        'value': {'key': 'value', 'type': '[BulkImportJob]'},
        'next_link': {'key': 'nextLink', 'type': 'str'},
    }

    def __init__(self, *, value, next_link: str=None, **kwargs) -> None:
        super(BulkImportJobCollection, self).__init__(**kwargs)
        self.value = value
        self.next_link = next_link
